import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 900, height: 980 }, deviceScaleFactor: 2 })
await ctx.addInitScript(() => { try { sessionStorage.setItem('cc-gate-override','1') } catch {} })
const p = await ctx.newPage()
await p.goto('http://localhost:3131/create', { waitUntil: 'networkidle' })
await p.waitForTimeout(800)
await p.fill('input[placeholder*="name your world"]', 'EMBER GARDEN')
await p.click('text=🖥 DESKTOP')
await p.click('text=○ OPEN WORLD')
await p.waitForTimeout(300)
await p.screenshot({ path: '/tmp/create-flow.png', fullPage: true })
console.log('shot saved')
await b.close()
