import type { Metadata, Viewport } from 'next'
import { Source_Serif_4, Libre_Franklin, IBM_Plex_Mono, Fraunces } from 'next/font/google'
import './globals.css'
import Beacon from './Beacon'
import { Providers } from './providers'
import SupportGate from './SupportGate'

const sourceSerif = Source_Serif_4({ subsets: ['latin'], variable: '--font-serif', display: 'swap' })
const libreFranklin = Libre_Franklin({ subsets: ['latin'], variable: '--font-sans', display: 'swap' })
const ibmPlexMono = IBM_Plex_Mono({ weight: ['400', '500'], subsets: ['latin'], variable: '--font-mono', display: 'swap' })
const fraunces = Fraunces({ subsets: ['latin'], variable: '--font-display', style: ['normal', 'italic'], axes: ['SOFT', 'WONK', 'opsz'], display: 'swap' })

const BRAND = process.env.NEXT_PUBLIC_BRAND_NAME || 'cartridge.cafe'

const DESC = 'Little worlds brewed by people and their AIs — visit any table, remix any recipe, leave yours on the shelf. Best on a desktop browser.'

export const metadata: Metadata = {
  // absolute-base for OG/twitter image URLs (auto-generated by opengraph-image.tsx)
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://cartridge.cafe'),
  title: {
    default: `${BRAND} — little worlds, served as single files`,
    template: `%s · ${BRAND}`,
  },
  description: DESC,
  openGraph: {
    type: 'website',
    siteName: BRAND,
    title: `${BRAND} — little worlds, served as single files`,
    description: DESC,
  },
  twitter: {
    card: 'summary_large_image',
    title: `${BRAND} — little worlds, served as single files`,
    description: DESC,
  },
}

export const viewport: Viewport = {
  themeColor: '#0c0a09',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sourceSerif.variable} ${libreFranklin.variable} ${ibmPlexMono.variable} ${fraunces.variable}`}>
      <body className="antialiased">
        <Providers><SupportGate>{children}</SupportGate></Providers>
        <Beacon />
      </body>
    </html>
  )
}
